In [101]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])

In [6]:
arr[0]

1

In [7]:
type(arr)#nd-n dimension

numpy.ndarray

In [12]:
arr[0:5:2]

array([1, 3, 5])

In [9]:
arr.ndim

1

In [10]:
arr.shape

(5,)

In [4]:
arr2=np.array([1,2,3,4,5,'hello','hi',True])

In [5]:
arr2.shape

(8,)

In [19]:
import sys
sys.getsizeof(list())

64

In [20]:
sys.getsizeof(np.array([]))

96

In [21]:
sys.getsizeof([1,2,3,4,5,6,7,8,9,10])

144

In [25]:
sys.getsizeof(np.array([1,2,3,4,5,6,7,8,9,10]))

136

# ways to create array

In [28]:
list1=[1,2,3,4,5,6]

In [29]:
arr1=np.array(list1)

In [31]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [43]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [58]:
np.linspace(1,100,num=20,endpoint=True,retstep=True,dtype=int)

(array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
         68,  73,  79,  84,  89,  94, 100]), 5.2105263157894735)

In [122]:
np.random.randint(1,6,size=2)

array([3, 5])

In [116]:
randArr=np.random.randint(10,100)

In [117]:
randArr

80

# multidimensional array

In [6]:
arr3=np.array([[1,2,3],[5,6,7],[8,9,4]])

In [7]:
arr3

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 4]])

In [14]:
arr3[0][0]

1

In [137]:
arr3.ndim

2

In [138]:
arr3.shape

(3, 3)

In [13]:
arr3[0:,0:2]

array([[1, 2],
       [5, 6],
       [8, 9]])

In [24]:
np.random.randint(10,100,[2,10])

array([[16, 29, 52, 82, 88, 58, 92, 50, 79, 29],
       [48, 89, 29, 85, 39, 37, 68, 41, 49, 98]])

#            # pandas intro

In [25]:
import pandas as pd

In [90]:
dict1={
    'names':['pant','sapola','goel'],
    'scores':[100,-10,80],
    'average':[21,0,80]
}

In [91]:
df=pd.DataFrame(dict1)

In [99]:
df[['scores','names']]

scores   names
0     100    pant
1     -10  sapola
2      80    goel

In [98]:
df[df['names']=='pant']

names  scores  average
0  pant     100       21

In [110]:
np.random.seed(5)

In [112]:
arr1=np.random.random(5)

In [114]:
arr1.max()

0.7659078564803156

In [116]:
arr1.argmin()

4

In [125]:
arr1=np.array([[1,3,2],[5,7,1]])

In [129]:
arr1.sort()

In [130]:
arr1

array([[1, 2, 3],
       [1, 5, 7]])